export default {
  Button: {
    primary: 'btn btn-primary',
    primaryOutline: 'btn btn-outline-primary',
    secondary: 'btn btn-secondary',
    secondaryOutline: 'btn btn-outline-secondary',
    success: 'btn btn-success',
    successOutline: 'btn btn-outline-success',
    danger: 'btn btn-danger',
    dangerOutline: 'btn btn-outline-danger',
    warning: 'btn btn-warning',
    warningOutline: 'btn btn-outline-warning',
    info: 'btn btn-info',
    infoOutline: 'btn btn-outline-info',
    light: 'btn btn-light',
    lightOutline: 'btn btn-outline-light',
    dark: 'btn btn-dark',
    darkOutline: 'btn btn-outline-dark',
  },
  ButtonSize: {
    sm: 'btn-sm',
    md: '',
    lg: 'btn-lg',
  },
  Alert: {
    primary: 'alert alert-primary',
    secondary: 'alert alert-secondary',
    success: 'alert alert-success',
    danger: 'alert alert-danger',
    warning: 'alert alert-warning',
    info: 'alert alert-info',
    light: 'alert alert-light',
    dark: 'alert alert-dark',
  },
  Badge: {
    primary: 'badge bg-primary',
    secondary: 'badge bg-secondary',
    success: 'badge bg-success',
    danger: 'badge bg-danger',
    warning: 'badge bg-warning',
    info: 'badge bg-info',
    light: 'badge bg-light',
    dark: 'badge bg-dark',
  },
  Checkbox: {
    container: 'form-check',
    input: 'form-check-input',
    label: 'form-check-label',
  },
  Hero: {
    container: `hero-container`,
    left: `hero-container__left`,
    right: `hero-container__right`,
    title: `hero-container__title`,
    description: `hero-container__description`,
    primaryLink: `hero-container__primary-link`,
    primaryIcon: `hero-container__primary-icon`,
    secondaryLink: `hero-container__secondary-link`,
  },
  Input: {
    input: 'form-control',
    label: 'form-label',
    helpText: 'form-text',
    asterisk: 'text-danger',
  },
  Select: {
    container: 'form-select-container',
    label: 'form-label',
    asterisk: 'text-danger',
    helpText: 'form-text',
    select: 'form-select',
  },
}
