export default {
  Button: {
    primary: 'btn btn-primary',
    primaryOutline: 'btn btn-outline-primary',
    secondary: 'btn btn-secondary',
    secondaryOutline: 'btn btn-outline-secondary',
    success: 'btn btn-success',
    successOutline: 'btn btn-outline-success',
    danger: 'btn btn-danger',
    dangerOutline: 'btn btn-outline-danger',
    warning: 'btn btn-warning',
    warningOutline: 'btn btn-outline-warning',
    info: 'btn btn-info',
    infoOutline: 'btn btn-outline-info',
    light: 'btn btn-light',
    lightOutline: 'btn btn-outline-light',
    dark: 'btn btn-dark',
    darkOutline: 'btn btn-outline-dark',
  },
  ButtonSize: {
    sm: 'btn-sm',
    md: '',
    lg: 'btn-lg',
  },
  Alert: {
    primary: 'alert alert-primary',
    secondary: 'alert alert-secondary',
    success: 'alert alert-success',
    danger: 'alert alert-danger',
    warning: 'alert alert-warning',
    info: 'alert alert-info',
    light: 'alert alert-light',
    dark: 'alert alert-dark',
  },
  Badge: {
    primary: 'badge bg-primary',
    secondary: 'badge bg-secondary',
    success: 'badge bg-success',
    danger: 'badge bg-danger',
    warning: 'badge bg-warning',
    info: 'badge bg-info',
    light: 'badge bg-light',
    dark: 'badge bg-dark',
  },
  Checkbox: {
    container: 'form-check',
    input: 'form-check-input',
    label: 'form-check-label',
  },
  Hero: {
    container: `container py-5 px-3 px-lg-4 row gx-lg-5 gy-4 align-items-center`,
    left: `col-lg-7`,
    right: `col-lg-5 d-none d-lg-flex justify-content-center`,
    title: `fw-bold display-4 mb-3 mb-md-4 lh-sm`,
    description: `text-muted mb-4 mb-lg-5 fs-5`,
    primaryLink: `btn btn-primary me-3 d-inline-flex align-items-center justify-content-center px-4 py-2 fs-6 fw-medium`,
    primaryIcon: `ms-2 text-white`,
    secondaryLink: `btn btn-outline-secondary d-inline-flex align-items-center justify-content-center px-4 py-2 fs-6 fw-medium text-dark`,
  },
  Input: {
    input: 'form-control',
    label: 'form-label',
    helpText: 'form-text mt-0 mb-1',
    asterisk: 'text-danger',
  },
  Select: {
    container: 'mb-4',
    label: 'form-label',
    asterisk: 'text-danger',
    helpText: 'form-text mt-0 mb-1',
    select: 'form-select',
  },
}
